version: '3.8'
services:
  server:
    container_name: challenge_server
    image: hgwright/challenge_server
    build: ./server
    deploy:
      replicas: 3
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
  number_api:
    container_name: challenge_number_api
    image: hgwright/challenge_number_api
    build: ./number_api
    deploy:
      replicas: 3
    ports:
    - published: 5001
      target: 5001
  prompt_api:
    container_name: challenge_prompt_api
    image: hgwright/challenge_prompt_api
    build: ./prompt_api
    deploy:
      replicas: 3
    ports:
    - published: 5002
      target: 5002
  word_api:
    container_name: challenge_word_api
    image: hgwright/challenge_word_api
    build: ./word_api
    deploy:
      replicas: 3
    ports:
    - published: 5003
      target: 5003
