---
- name: Add worker to swarm
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    join_token: "{{ hostvars['35.246.120.139']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ '35.246.120.139:2377' ]